### ISSUE TITLE
Only able to retrieve first page of response

### ISSUE THREAD

**Issue by jeffweiss** [edgurgel/tentacat#67]
For API requests that have a large number of results, we're only returning the first page. Additionally because the headers are thrown away in the `process_response` call, we have no way to tell the user, "Hey, there are more pages to what you asked for."

Here's a `link` header from the call to `Tentacat.Repositories.list_users("jeffweiss")`
```elixir
  {"X-GitHub-Media-Type", "github.v3; format=json"},
  {"Link",
   "<https://api.github.com/user/818053/repos?page=2>; rel=\"next\", <https://api.github.com/user/818053/repos?page=5>; rel=\"last\""},
```

**Comment by edgurgel** [comment]
This would involve a breaking change on the way we pass the response back to the user. Should we simply pass the `HTTPoison.Response` struct and let the user deal with it? cc/ @duksis

**Comment by jeffweiss** [comment]
I think we can handle this without breaking capability for existing functions. We can add pagination versions of the necessary functions. We can then add a small `Stream` layer atop that. Finally we can refactor the exist functions to be `Enum.all(stream)`.

If I have time over the next couple evenings I can attempt to put something together. 

Sent from my iPhone

**Comment by edgurgel** [comment]
We could check if the headers have a "Link" and pass a different response in this case? Something like `request_with_pagination` and use this one instead of the ones we already have.

`{decoded_boy, next_url}`Instead of the decoded body

I think this `Stream` idea shouldn't be part of this change as it's just sugar on top of the actual implementation? Specially that some people may not need all the pages for example.

**Comment by jeffweiss** [comment]
I don't think the `Stream` aspect is simply sugar, mostly because I don't believe that the default user intent for calls to any of those functions is "Hey, get me explicitly only the first 30 repositories" (for example). My interpretation reading the docs and from looking at honeypotio's usage is that the intent is to get *all* the repos for a user and *all* the public activity from the last 90 days.

I definitely believe there should be `request_with_pagination` functionality in addition to get-all-the-things for those that *explicitly* want pagination.

The tiers of usage that I perceive are (in what I believe is an increasing share of implicit intent, if you will):
1. `request_with_pagination` - "I know there are pages, I want to handle the pages myself for X reason"
2. `request_stream` - "I don't want to wait for all of them to be retrieved, but pagination is a pain in the ass"
3. `request` - "I need all the things. Pages? API rate limit? What are those???"

Architecturally, I see `request_stream` being built upon `request_with_pagination` and `request` built upon `request_stream`.

**Comment by edgurgel** [comment]
I think we are agreeing on the same thing. I just wouldn't like to enforce users to stream everything. As long as we have it as an option I'm fine with it. :+1:

**Comment by jeffweiss** [comment]
I have an initial implementation over at https://github.com/jeffweiss/tentacat/tree/add_pagination. I have a handful of addition vcr cassettes that I need to pare down before I add them. First I need sleep though. I should be able to open in the PR in the next day or so...

**Comment by duksis** [comment]
we could keep the same public interface and return a stream when there is something to paginate and everything otherwise. Downside is that we would force users to handle both stream and non stream responses.
The `Enum.all(stream)` approach sounds nice as it will actually work as the majority would expect, but there will be issues with endpoints like [Tentacat.Repositories.list_public](https://github.com/edgurgel/tentacat/blob/master/lib/tentacat/repositories.ex#L61..L66) which would end up returning all public repositories on github :)

Anyway we need to be able to fetch more than the first page with tentacat so a PR would be very much appreciated @jeffweiss

**Comment by jeffweiss** [comment]
Thanks for the feedback @duksis. :+1:  The handful of never-ending streams like list public repos and list users now default to just a single page, with the option to override either with a `Stream` or auto-pagination.
